# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BreezyStudios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Analytics'

  # Pods for BreezyStudios

  target 'BreezyStudiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BreezyStudiosUITests' do
    # Pods for testing
  end

end
